### ISSUE TITLE
Changing the number of classes

### ISSUE THREAD

**Issue by ShechemKS** [yikun2019/PENCIL#3]
I am traying to use the PENCIL framework to train an custom model on a custom dataset, with 5 classes. When I run the model, I get the error 
`Traceback (most recent call last):
  File "PENCIL.py", line 512, in <module>
    main()
  File "PENCIL.py", line 299, in main
    train(trainloader, model, criterion, optimizer, epoch, y)
  File "PENCIL.py", line 353, in train
    new_y[index, :] = onehot
ValueError: shape mismatch: value array of shape (16,10) could not be broadcast to indexing result of shape (16,5)`

The creation of the onehot tensor is given in line 351:
`            onehot = torch.zeros(target.size(0), 10).scatter_(1, target.view(-1, 1), 10.0)
`

Should I change only the 1st 10 in the code, and keep the "10.0", or change that to "5.0". What exactly does this line do?

**Comment by oy-ilho** [comment]
I think you should change the 1st 10. 
But The "10.0" is not related on changing class number. because the "10.0" means K on the eq.8 y~ = Ky^ at the paper.
